name: mangabackupconverter_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  aidoku_plugin_loader:
    path: ../aidoku_plugin_loader
  archive: ^4.0.0
  args: ^2.4.2
  characters: ^1.3.0
  collection: ^1.19.0
  dart_mappable: ^4.2.2
  ffi: ^2.2.0
  fixnum: ^1.1.1
  http: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  propertylistserialization: ^1.4.0
  protobuf: ^3.1.0
  sqflite_common: ^2.5.4
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.4
  uuid: ^4.5.3
  win32: ^5.15.0
  xcode_parser: ^1.2.1
dev_dependencies:
  app_lints:
    path: ../app_lints
  build_runner: ^2.4.11
  checks: ^0.3.0
  dart_mappable_builder: ^4.2.3
  test: ^1.24.0

platforms:
  ios:
  android:
  windows:
  macos:
  linux:
  web:
