name: wasm_plugin_loader
description: WASM plugin loader for Aidoku source plugins. Enables manga ID resolution during backup conversion.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0
resolution: workspace

dependencies:
  archive: ^4.0.0
  collection: ^1.19.0
  html: ^0.15.4
  http: ^1.2.0
  meta: ^1.12.0
  wasm_ffi: ^2.2.0

dev_dependencies:
  app_lints:
    path: ../app_lints
  test: ^1.24.0

platforms:
  ios:
  android:
  windows:
  macos:
  linux:
  web:
