name: aidoku_plugin_loader
description: WASM plugin loader for Aidoku source plugins. Enables manga ID resolution during backup conversion.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0
resolution: workspace

dependencies:
  archive: ^4.0.0
  collection: ^1.19.0
  ffi: ^2.2.0
  http: ^1.2.0
  image: ^4.5.3
  jsoup:
    path: ../jsoup
  meta: ^1.12.0
  universal_ffi: ^1.4.0
  wasm3:
    path: ../wasm3
  wasm_ffi: ^2.2.0
  wasm_runner:
    path: ../wasm_runner
  web_wasm_runner:
    path: ../web_wasm_runner

dev_dependencies:
  app_lints:
    path: ../app_lints
  checks: ^0.3.0
  test: ^1.24.0

  jni: any
platforms:
  ios:
  android:
  windows:
  macos:
  linux:
  web:
