name: web_wasm_runner
description: Browser WebAssembly runner implementing the wasm_runner interface.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0
resolution: workspace

dependencies:
  wasm_runner:
    path: ../wasm_runner

dev_dependencies:
  app_lints:
    path: ../app_lints
  checks: ^0.3.0
  test: ^1.24.0

platforms:
  web:
