name: env
description: A new Flutter package which provides environment variables for the
  app. These variables can also be obfuscated.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  envied: ^1.3.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  hooks_riverpod: ^3.0.0

dev_dependencies:
  app_lints:
    path: ../app_lints
  build_runner: ^2.4.5
  envied_generator: ^1.3.0
  flutter_test:
    sdk: flutter
# flutter:
